on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        - target: x86_64-unknown-linux-musl
          archive: tar.gz tar.xz tar.zst
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          RUSTTARGET: ${{ matrix.target }}
